# Generated by Django 4.1.5 on 2023-01-16 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ed52b4f-1e5f-4dc3-8e2f-09ab9dcea4e2'), primary_key=True, serialize=False),
        ),
    ]
