# Generated by Django 4.1.5 on 2023-02-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
        ('users', '0002_alter_user_id_todo_project'),
    ]

    operations = [
    ]
